all: enemy.o search_player.o random_move.o damage_player.o push_player.o

enemy.o: lb_7/enemy.cc lb_7/headers/enemy.h 
	g++ -c lb_7/enemy.cc 

search_player.o: lb_7/search_player.cc lb_7/headers/search_player.h
	g++ -c lb_7/search_player.cc 

random_move.o: lb_7/random_move.cc lb_7/headers/random_move.h 
	g++ -c lb_7/random_move.cc

damage_player.o: lb_7/damage_player.cc lb_7/headers/damage_player.h
	g++ -c lb_7/damage_player.cc

push_player.o: lb_7/push_player.cc lb_7/headers/push_player.h
	g++ -c lb_7/push_player.cc